/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Dyl
 */
public class FrmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        TabPane = new javax.swing.JTabbedPane();
        pnlPrincipal = new javax.swing.JPanel();
        pnlClientes = new javax.swing.JPanel();
        scTablaClientes = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        txtMostrandoClientes = new javax.swing.JLabel();
        btnAnteriorCliente = new javax.swing.JButton();
        btnSiguienteCliente = new javax.swing.JButton();
        separadorCliente = new javax.swing.JSeparator();
        btnBuscarCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnBorrarCliente = new javax.swing.JButton();
        btnCrearCliente = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        SeparadorTCliente = new javax.swing.JSeparator();
        btnTelefonosCliente = new javax.swing.JButton();
        pnlConductores = new javax.swing.JPanel();
        scTablaConductores = new javax.swing.JScrollPane();
        tbConductores = new javax.swing.JTable();
        txtMostrandoConductor = new javax.swing.JLabel();
        btnAnteriorConductores = new javax.swing.JButton();
        btnSiguienteConductores = new javax.swing.JButton();
        separadorConductores = new javax.swing.JSeparator();
        btnBuscarConductores = new javax.swing.JButton();
        btnEditarConductores = new javax.swing.JButton();
        btnBorrarConductores = new javax.swing.JButton();
        btnCrearConductores = new javax.swing.JButton();
        lblConductores = new javax.swing.JLabel();
        SeparadorTConductores = new javax.swing.JSeparator();
        btnTelefonosConductores = new javax.swing.JButton();
        btnTelefonosConductores1 = new javax.swing.JButton();
        pnlVehiculos = new javax.swing.JPanel();
        scTablaVehiculos = new javax.swing.JScrollPane();
        tbVehiculos = new javax.swing.JTable();
        txtMostrandoVehiculos = new javax.swing.JLabel();
        btnAnteriorVehiculosVehiculos = new javax.swing.JButton();
        btnSiguienteVehiculos = new javax.swing.JButton();
        separadorVehiculos = new javax.swing.JSeparator();
        btnBuscarVehiculos = new javax.swing.JButton();
        btnEditarVehiculos = new javax.swing.JButton();
        btnBorrarVehiculos = new javax.swing.JButton();
        btnCrearVehiculos = new javax.swing.JButton();
        lblVehiculos = new javax.swing.JLabel();
        SeparadorTVehiculos = new javax.swing.JSeparator();
        btnBuscarVehiculos1 = new javax.swing.JButton();
        pnlServicios = new javax.swing.JPanel();
        scTablaServicios = new javax.swing.JScrollPane();
        tbServicios = new javax.swing.JTable();
        txtMostrandoServicios = new javax.swing.JLabel();
        btnAnteriorServicios = new javax.swing.JButton();
        btnSiguienteServicios = new javax.swing.JButton();
        separadorServicios = new javax.swing.JSeparator();
        btnBuscarServicios = new javax.swing.JButton();
        btnEditarServicios = new javax.swing.JButton();
        btnBorrarServicios = new javax.swing.JButton();
        btnCrearServicios = new javax.swing.JButton();
        lblServicios = new javax.swing.JLabel();
        SeparadorTServicios = new javax.swing.JSeparator();
        btnMasDetallesServicios = new javax.swing.JButton();
        pnlBusquedaAvanzada = new javax.swing.JPanel();
        pnlConfiguracion = new javax.swing.JPanel();
        separadorConfiguracion = new javax.swing.JSeparator();
        lblConfiguracion = new javax.swing.JLabel();
        SeparadorTConfiguracion = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pnlInferior = new javax.swing.JPanel();
        SeparadorPanel = new javax.swing.JSeparator();
        btnCerrarSesion = new javax.swing.JButton();
        SeparadorPanelT = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        TabPane.setBackground(new java.awt.Color(81, 107, 122));
        TabPane.setForeground(new java.awt.Color(255, 255, 255));
        TabPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabPane.setFocusable(false);
        TabPane.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        TabPane.addTab("Panel Principal", pnlPrincipal);

        pnlClientes.setBackground(new java.awt.Color(255, 255, 255));

        scTablaClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        scTablaClientes.setFocusable(false);

        tbClientes.setAutoCreateRowSorter(true);
        tbClientes.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Direccion", "Genero", "Nacionalidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbClientes.setToolTipText("");
        tbClientes.setShowGrid(false);
        scTablaClientes.setViewportView(tbClientes);
        tbClientes.getAccessibleContext().setAccessibleName("");

        txtMostrandoClientes.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        txtMostrandoClientes.setText("Mostrando 1 de 50");

        btnAnteriorCliente.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnAnteriorCliente.setText("Anterior");

        btnSiguienteCliente.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnSiguienteCliente.setText("Siguiente");

        separadorCliente.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnBuscarCliente.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBuscarCliente.setText("Buscar");

        btnEditarCliente.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnEditarCliente.setText("Editar");

        btnBorrarCliente.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBorrarCliente.setText("Borrar");

        btnCrearCliente.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnCrearCliente.setText("Crear");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        lblCliente.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        lblCliente.setText("Clientes");

        btnTelefonosCliente.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnTelefonosCliente.setText("Teléfonos");
        btnTelefonosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonosClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addComponent(separadorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(lblCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTelefonosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlClientesLayout.createSequentialGroup()
                                .addComponent(txtMostrandoClientes)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnteriorCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiguienteCliente))
                            .addComponent(scTablaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)))
                    .addComponent(SeparadorTCliente))
                .addGap(17, 17, 17))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(btnCrearCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTelefonosCliente))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(scTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMostrandoClientes)
                            .addComponent(btnAnteriorCliente)
                            .addComponent(btnSiguienteCliente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addComponent(separadorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabPane.addTab("Clientes", pnlClientes);

        pnlConductores.setBackground(new java.awt.Color(255, 255, 255));

        scTablaConductores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        scTablaConductores.setFocusable(false);

        tbConductores.setAutoCreateRowSorter(true);
        tbConductores.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        tbConductores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Foto", "Nombre", "Direccion", "Genero", "Nacionalidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbConductores.setToolTipText("");
        tbConductores.setShowGrid(false);
        scTablaConductores.setViewportView(tbConductores);

        txtMostrandoConductor.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        txtMostrandoConductor.setText("Mostrando 1 de 50");

        btnAnteriorConductores.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnAnteriorConductores.setText("Anterior");

        btnSiguienteConductores.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnSiguienteConductores.setText("Siguiente");

        separadorConductores.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnBuscarConductores.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBuscarConductores.setText("Buscar");

        btnEditarConductores.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnEditarConductores.setText("Editar");

        btnBorrarConductores.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBorrarConductores.setText("Borrar");

        btnCrearConductores.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnCrearConductores.setText("Crear");
        btnCrearConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearConductoresActionPerformed(evt);
            }
        });

        lblConductores.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        lblConductores.setText("Conductores");

        btnTelefonosConductores.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnTelefonosConductores.setText("Teléfonos");
        btnTelefonosConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonosConductoresActionPerformed(evt);
            }
        });

        btnTelefonosConductores1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnTelefonosConductores1.setText("Vehiculos");
        btnTelefonosConductores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonosConductores1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConductoresLayout = new javax.swing.GroupLayout(pnlConductores);
        pnlConductores.setLayout(pnlConductoresLayout);
        pnlConductoresLayout.setHorizontalGroup(
            pnlConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConductoresLayout.createSequentialGroup()
                .addComponent(separadorConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConductoresLayout.createSequentialGroup()
                        .addComponent(lblConductores)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlConductoresLayout.createSequentialGroup()
                        .addGroup(pnlConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarConductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarConductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarConductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearConductores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTelefonosConductores, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(btnTelefonosConductores1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConductoresLayout.createSequentialGroup()
                                .addComponent(txtMostrandoConductor)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnteriorConductores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiguienteConductores))
                            .addComponent(scTablaConductores, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)))
                    .addComponent(SeparadorTConductores))
                .addGap(17, 17, 17))
        );
        pnlConductoresLayout.setVerticalGroup(
            pnlConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConductoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblConductores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorTConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConductoresLayout.createSequentialGroup()
                        .addComponent(btnCrearConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTelefonosConductores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTelefonosConductores1))
                    .addGroup(pnlConductoresLayout.createSequentialGroup()
                        .addComponent(scTablaConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlConductoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMostrandoConductor)
                            .addComponent(btnAnteriorConductores)
                            .addComponent(btnSiguienteConductores))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlConductoresLayout.createSequentialGroup()
                .addComponent(separadorConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabPane.addTab("Conductores", pnlConductores);

        pnlVehiculos.setBackground(new java.awt.Color(255, 255, 255));

        scTablaVehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        scTablaVehiculos.setFocusable(false);

        tbVehiculos.setAutoCreateRowSorter(true);
        tbVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        tbVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Placa", "Modelo", "Marca", "Tipo de servicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVehiculos.setToolTipText("");
        tbVehiculos.setShowGrid(false);
        scTablaVehiculos.setViewportView(tbVehiculos);

        txtMostrandoVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        txtMostrandoVehiculos.setText("Mostrando 1 de 50");

        btnAnteriorVehiculosVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnAnteriorVehiculosVehiculos.setText("Anterior");

        btnSiguienteVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnSiguienteVehiculos.setText("Siguiente");

        separadorVehiculos.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnBuscarVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBuscarVehiculos.setText("Buscar");

        btnEditarVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnEditarVehiculos.setText("Editar");

        btnBorrarVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBorrarVehiculos.setText("Borrar");

        btnCrearVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnCrearVehiculos.setText("Crear");
        btnCrearVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVehiculosActionPerformed(evt);
            }
        });

        lblVehiculos.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        lblVehiculos.setText("Vehículos");

        btnBuscarVehiculos1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBuscarVehiculos1.setText("Conductores");
        btnBuscarVehiculos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVehiculos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVehiculosLayout = new javax.swing.GroupLayout(pnlVehiculos);
        pnlVehiculos.setLayout(pnlVehiculosLayout);
        pnlVehiculosLayout.setHorizontalGroup(
            pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehiculosLayout.createSequentialGroup()
                .addComponent(separadorVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehiculosLayout.createSequentialGroup()
                        .addComponent(lblVehiculos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlVehiculosLayout.createSequentialGroup()
                        .addGroup(pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarVehiculos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVehiculosLayout.createSequentialGroup()
                                .addComponent(txtMostrandoVehiculos)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnteriorVehiculosVehiculos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiguienteVehiculos))
                            .addComponent(scTablaVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)))
                    .addComponent(SeparadorTVehiculos))
                .addGap(17, 17, 17))
        );
        pnlVehiculosLayout.setVerticalGroup(
            pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehiculosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorTVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehiculosLayout.createSequentialGroup()
                        .addComponent(btnCrearVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVehiculosLayout.createSequentialGroup()
                        .addComponent(scTablaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMostrandoVehiculos)
                            .addComponent(btnAnteriorVehiculosVehiculos)
                            .addComponent(btnSiguienteVehiculos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlVehiculosLayout.createSequentialGroup()
                .addComponent(separadorVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabPane.addTab("Vehículos", pnlVehiculos);

        pnlServicios.setBackground(new java.awt.Color(255, 255, 255));

        scTablaServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        scTablaServicios.setFocusable(false);

        tbServicios.setAutoCreateRowSorter(true);
        tbServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        tbServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Valor", "Origen", "Destino", "Conductor", "Cliente", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbServicios.setToolTipText("");
        tbServicios.setShowGrid(false);
        scTablaServicios.setViewportView(tbServicios);

        txtMostrandoServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        txtMostrandoServicios.setText("Mostrando 1 de 50");

        btnAnteriorServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnAnteriorServicios.setText("Anterior");
        btnAnteriorServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorServiciosActionPerformed(evt);
            }
        });

        btnSiguienteServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnSiguienteServicios.setText("Siguiente");

        separadorServicios.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnBuscarServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBuscarServicios.setText("Buscar");

        btnEditarServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnEditarServicios.setText("Editar");

        btnBorrarServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBorrarServicios.setText("Borrar");

        btnCrearServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnCrearServicios.setText("Crear");
        btnCrearServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearServiciosActionPerformed(evt);
            }
        });

        lblServicios.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        lblServicios.setText("Servicios");

        btnMasDetallesServicios.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnMasDetallesServicios.setText("Mas Detalles");
        btnMasDetallesServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasDetallesServiciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlServiciosLayout = new javax.swing.GroupLayout(pnlServicios);
        pnlServicios.setLayout(pnlServiciosLayout);
        pnlServiciosLayout.setHorizontalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addComponent(separadorServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(lblServicios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMasDetallesServicios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlServiciosLayout.createSequentialGroup()
                                .addComponent(txtMostrandoServicios)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnteriorServicios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiguienteServicios))
                            .addComponent(scTablaServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)))
                    .addComponent(SeparadorTServicios))
                .addGap(17, 17, 17))
        );
        pnlServiciosLayout.setVerticalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorTServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(btnCrearServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMasDetallesServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(scTablaServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMostrandoServicios)
                            .addComponent(btnAnteriorServicios)
                            .addComponent(btnSiguienteServicios))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addComponent(separadorServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabPane.addTab("Servicios", pnlServicios);

        pnlBusquedaAvanzada.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBusquedaAvanzadaLayout = new javax.swing.GroupLayout(pnlBusquedaAvanzada);
        pnlBusquedaAvanzada.setLayout(pnlBusquedaAvanzadaLayout);
        pnlBusquedaAvanzadaLayout.setHorizontalGroup(
            pnlBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        pnlBusquedaAvanzadaLayout.setVerticalGroup(
            pnlBusquedaAvanzadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        TabPane.addTab("Busqueda Avanzada", pnlBusquedaAvanzada);

        pnlConfiguracion.setBackground(new java.awt.Color(255, 255, 255));

        separadorConfiguracion.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblConfiguracion.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        lblConfiguracion.setText("Configuración");

        jLabel1.setText("Ubicación base de datos");

        jTextField1.setText("C:\\Users\\Usuario\\.PgAdmin\\");

            jButton2.setText("Buscar");

            javax.swing.GroupLayout pnlConfiguracionLayout = new javax.swing.GroupLayout(pnlConfiguracion);
            pnlConfiguracion.setLayout(pnlConfiguracionLayout);
            pnlConfiguracionLayout.setHorizontalGroup(
                pnlConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlConfiguracionLayout.createSequentialGroup()
                    .addComponent(separadorConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlConfiguracionLayout.createSequentialGroup()
                            .addComponent(lblConfiguracion)
                            .addGap(0, 871, Short.MAX_VALUE))
                        .addGroup(pnlConfiguracionLayout.createSequentialGroup()
                            .addComponent(SeparadorTConfiguracion)
                            .addGap(17, 17, 17))
                        .addGroup(pnlConfiguracionLayout.createSequentialGroup()
                            .addGroup(pnlConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(pnlConfiguracionLayout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            );
            pnlConfiguracionLayout.setVerticalGroup(
                pnlConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlConfiguracionLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(lblConfiguracion)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(SeparadorTConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlConfiguracionLayout.createSequentialGroup()
                    .addComponent(separadorConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            TabPane.addTab("Configuración", pnlConfiguracion);

            javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
            pnlFondo.setLayout(pnlFondoLayout);
            pnlFondoLayout.setHorizontalGroup(
                pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TabPane, javax.swing.GroupLayout.Alignment.TRAILING)
            );
            pnlFondoLayout.setVerticalGroup(
                pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pnlInferior.setBackground(new java.awt.Color(255, 255, 255));

            SeparadorPanel.setOrientation(javax.swing.SwingConstants.VERTICAL);

            btnCerrarSesion.setBackground(new java.awt.Color(250, 39, 51));
            btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
            btnCerrarSesion.setText("Cerrar Sesion");
            btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCerrarSesionActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
            pnlInferior.setLayout(pnlInferiorLayout);
            pnlInferiorLayout.setHorizontalGroup(
                pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInferiorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SeparadorPanelT)
                        .addGroup(pnlInferiorLayout.createSequentialGroup()
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SeparadorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
            );
            pnlInferiorLayout.setVerticalGroup(
                pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInferiorLayout.createSequentialGroup()
                    .addComponent(SeparadorPanelT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SeparadorPanel))
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(pnlInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void btnTelefonosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonosClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTelefonosClienteActionPerformed

    private void btnCrearConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearConductoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearConductoresActionPerformed

    private void btnTelefonosConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonosConductoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTelefonosConductoresActionPerformed

    private void btnCrearVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearVehiculosActionPerformed

    private void btnTelefonosConductores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonosConductores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTelefonosConductores1ActionPerformed

    private void btnBuscarVehiculos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVehiculos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarVehiculos1ActionPerformed

    private void btnCrearServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearServiciosActionPerformed

    private void btnMasDetallesServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasDetallesServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasDetallesServiciosActionPerformed

    private void btnAnteriorServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorServiciosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SeparadorPanel;
    private javax.swing.JSeparator SeparadorPanelT;
    private javax.swing.JSeparator SeparadorTCliente;
    private javax.swing.JSeparator SeparadorTConductores;
    private javax.swing.JSeparator SeparadorTConfiguracion;
    private javax.swing.JSeparator SeparadorTServicios;
    private javax.swing.JSeparator SeparadorTVehiculos;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JButton btnAnteriorCliente;
    private javax.swing.JButton btnAnteriorConductores;
    private javax.swing.JButton btnAnteriorServicios;
    private javax.swing.JButton btnAnteriorVehiculosVehiculos;
    private javax.swing.JButton btnBorrarCliente;
    private javax.swing.JButton btnBorrarConductores;
    private javax.swing.JButton btnBorrarServicios;
    private javax.swing.JButton btnBorrarVehiculos;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarConductores;
    private javax.swing.JButton btnBuscarServicios;
    private javax.swing.JButton btnBuscarVehiculos;
    private javax.swing.JButton btnBuscarVehiculos1;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnCrearConductores;
    private javax.swing.JButton btnCrearServicios;
    private javax.swing.JButton btnCrearVehiculos;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarConductores;
    private javax.swing.JButton btnEditarServicios;
    private javax.swing.JButton btnEditarVehiculos;
    private javax.swing.JButton btnMasDetallesServicios;
    private javax.swing.JButton btnSiguienteCliente;
    private javax.swing.JButton btnSiguienteConductores;
    private javax.swing.JButton btnSiguienteServicios;
    private javax.swing.JButton btnSiguienteVehiculos;
    private javax.swing.JButton btnTelefonosCliente;
    private javax.swing.JButton btnTelefonosConductores;
    private javax.swing.JButton btnTelefonosConductores1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblConductores;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblServicios;
    private javax.swing.JLabel lblVehiculos;
    private javax.swing.JPanel pnlBusquedaAvanzada;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlConductores;
    private javax.swing.JPanel pnlConfiguracion;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlServicios;
    private javax.swing.JPanel pnlVehiculos;
    private javax.swing.JScrollPane scTablaClientes;
    private javax.swing.JScrollPane scTablaConductores;
    private javax.swing.JScrollPane scTablaServicios;
    private javax.swing.JScrollPane scTablaVehiculos;
    private javax.swing.JSeparator separadorCliente;
    private javax.swing.JSeparator separadorConductores;
    private javax.swing.JSeparator separadorConfiguracion;
    private javax.swing.JSeparator separadorServicios;
    private javax.swing.JSeparator separadorVehiculos;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTable tbConductores;
    private javax.swing.JTable tbServicios;
    private javax.swing.JTable tbVehiculos;
    private javax.swing.JLabel txtMostrandoClientes;
    private javax.swing.JLabel txtMostrandoConductor;
    private javax.swing.JLabel txtMostrandoServicios;
    private javax.swing.JLabel txtMostrandoVehiculos;
    // End of variables declaration//GEN-END:variables
}
