/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Dyl
 */
public class IFrmAddModGenerico extends javax.swing.JInternalFrame {

    public JSeparator getSeparadorAddMod() {
        return SeparadorAddMod;
    }

    public void setSeparadorAddMod(JSeparator SeparadorAddMod) {
        this.SeparadorAddMod = SeparadorAddMod;
    }

    public JButton getBtnAddMod() {
        return btnAddMod;
    }

    public void setBtnAddMod(JButton btnAddMod) {
        this.btnAddMod = btnAddMod;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JComboBox<String> getCmbCarac2() {
        return cmbCarac2;
    }

    public void setCmbCarac2(JComboBox<String> cmbCarac2) {
        this.cmbCarac2 = cmbCarac2;
    }

    public JLabel getLblAddMod() {
        return lblAddMod;
    }

    public void setLblAddMod(JLabel lblAddMod) {
        this.lblAddMod = lblAddMod;
    }

    public JLabel getLblCarac1() {
        return lblCarac1;
    }

    public void setLblCarac1(JLabel lblCarac1) {
        this.lblCarac1 = lblCarac1;
    }

    public JLabel getLblCarac2() {
        return lblCarac2;
    }

    public void setLblCarac2(JLabel lblCarac2) {
        this.lblCarac2 = lblCarac2;
    }

    public JLabel getLblCarac3() {
        return lblCarac3;
    }

    public void setLblCarac3(JLabel lblCarac3) {
        this.lblCarac3 = lblCarac3;
    }

    public JPanel getPnlAddMod() {
        return pnlAddMod;
    }

    public void setPnlAddMod(JPanel pnlAddMod) {
        this.pnlAddMod = pnlAddMod;
    }

    public JScrollPane getScTbCarac3() {
        return scTbCarac3;
    }

    public void setScTbCarac3(JScrollPane scTbCarac3) {
        this.scTbCarac3 = scTbCarac3;
    }

    public JTable getTbCarac3() {
        return tbCarac3;
    }

    public void setTbCarac3(JTable tbCarac3) {
        this.tbCarac3 = tbCarac3;
    }

    public JTextField getTxtCarac1() {
        return txtCarac1;
    }

    public void setTxtCarac1(JTextField txtCarac1) {
        this.txtCarac1 = txtCarac1;
    }

    /**
     * Creates new form IFrmAddModGenerico
     */
    public IFrmAddModGenerico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddMod = new javax.swing.JPanel();
        lblAddMod = new javax.swing.JLabel();
        SeparadorAddMod = new javax.swing.JSeparator();
        lblCarac1 = new javax.swing.JLabel();
        txtCarac1 = new javax.swing.JTextField();
        lblCarac2 = new javax.swing.JLabel();
        cmbCarac2 = new javax.swing.JComboBox<>();
        lblCarac3 = new javax.swing.JLabel();
        scTbCarac3 = new javax.swing.JScrollPane();
        tbCarac3 = new javax.swing.JTable();
        btnAddMod = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        pnlAddMod.setBackground(new java.awt.Color(255, 255, 255));

        lblAddMod.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        lblAddMod.setText("Crear/Modificar un nuevo elemento");

        lblCarac1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        lblCarac1.setText("Caracteristica 1");

        txtCarac1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N

        lblCarac2.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        lblCarac2.setText("Caracteristica 2");

        cmbCarac2.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        cmbCarac2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCarac3.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        lblCarac3.setText("Caracteristica 3");

        tbCarac3.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        tbCarac3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scTbCarac3.setViewportView(tbCarac3);

        btnAddMod.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnAddMod.setText("CREAR/MODIFICAR");

        btnCancelar.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout pnlAddModLayout = new javax.swing.GroupLayout(pnlAddMod);
        pnlAddMod.setLayout(pnlAddModLayout);
        pnlAddModLayout.setHorizontalGroup(
            pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddModLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeparadorAddMod)
                    .addGroup(pnlAddModLayout.createSequentialGroup()
                        .addComponent(lblAddMod)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddModLayout.createSequentialGroup()
                        .addGroup(pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarac1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarac2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarac3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddModLayout.createSequentialGroup()
                                .addComponent(btnAddMod)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addGroup(pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCarac1)
                                .addComponent(cmbCarac2, 0, 288, Short.MAX_VALUE)
                                .addComponent(scTbCarac3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlAddModLayout.setVerticalGroup(
            pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddModLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblAddMod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorAddMod, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarac1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCarac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarac2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarac3)
                    .addComponent(scTbCarac3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMod)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SeparadorAddMod;
    private javax.swing.JButton btnAddMod;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbCarac2;
    private javax.swing.JLabel lblAddMod;
    private javax.swing.JLabel lblCarac1;
    private javax.swing.JLabel lblCarac2;
    private javax.swing.JLabel lblCarac3;
    private javax.swing.JPanel pnlAddMod;
    private javax.swing.JScrollPane scTbCarac3;
    private javax.swing.JTable tbCarac3;
    private javax.swing.JTextField txtCarac1;
    // End of variables declaration//GEN-END:variables
}
