/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Crear;

import Vista.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Dyl
 */
public class IFrmTelefonos extends javax.swing.JInternalFrame {

    public JComboBox<String> getCmbTelefonos() {
        return cmbTelefonos;
    }

    public void setCmbTelefonos(JComboBox<String> cmbTelefonos) {
        this.cmbTelefonos = cmbTelefonos;
    }

 

    public JTextField getTxtNueNumero() {
        return txtNueNumero;
    }

    public void setTxtNueNumero(JTextField txtNueNumero) {
        this.txtNueNumero = txtNueNumero;
    }

    public JSeparator getSeparadorTelefonos() {
        return SeparadorTelefonos;
    }

    public void setSeparadorTelefonos(JSeparator SeparadorTelefonos) {
        this.SeparadorTelefonos = SeparadorTelefonos;
    }

    public JButton getBtnAddTelefonos() {
        return btnAddTelefonos;
    }

    public void setBtnAddTelefonos(JButton btnAddTelefonos) {
        this.btnAddTelefonos = btnAddTelefonos;
    }

    public JButton getBtnBorrarTelefonos() {
        return btnBorrarTelefonos;
    }

    public void setBtnBorrarTelefonos(JButton btnBorrarTelefonos) {
        this.btnBorrarTelefonos = btnBorrarTelefonos;
    }

    public JButton getBtnEditTelefonos() {
        return btnEditTelefonos;
    }

    public void setBtnEditTelefonos(JButton btnEditTelefonos) {
        this.btnEditTelefonos = btnEditTelefonos;
    }

    public JLabel getLblTelefonos() {
        return lblTelefonos;
    }

    public void setLblTelefonos(JLabel lblTelefonos) {
        this.lblTelefonos = lblTelefonos;
    }

    public JList<String> getLsTelefonos() {
        return lsTelefonos;
    }

    public void setLsTelefonos(JList<String> lsTelefonos) {
        this.lsTelefonos = lsTelefonos;
    }

    public JPanel getPnlTelefonos() {
        return pnlTelefonos;
    }

    public void setPnlTelefonos(JPanel pnlTelefonos) {
        this.pnlTelefonos = pnlTelefonos;
    }

    public JScrollPane getScLsTelefonos() {
        return scLsTelefonos;
    }

    public void setScLsTelefonos(JScrollPane scLsTelefonos) {
        this.scLsTelefonos = scLsTelefonos;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    /**
     * Creates new form IFrmAddModGenerico
     */
    public IFrmTelefonos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelefonos = new javax.swing.JPanel();
        lblTelefonos = new javax.swing.JLabel();
        SeparadorTelefonos = new javax.swing.JSeparator();
        btnBorrarTelefonos = new javax.swing.JButton();
        btnAddTelefonos = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        btnEditTelefonos = new javax.swing.JButton();
        scLsTelefonos = new javax.swing.JScrollPane();
        lsTelefonos = new javax.swing.JList<>();
        txtNueNumero = new javax.swing.JTextField();
        cmbTelefonos = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        pnlTelefonos.setBackground(new java.awt.Color(255, 255, 255));

        lblTelefonos.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        lblTelefonos.setText("Telefónos de");

        btnBorrarTelefonos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnBorrarTelefonos.setText("BORRAR");
        btnBorrarTelefonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTelefonosActionPerformed(evt);
            }
        });

        btnAddTelefonos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnAddTelefonos.setText("AGREGAR");
        btnAddTelefonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTelefonosActionPerformed(evt);
            }
        });

        btnEditTelefonos.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        btnEditTelefonos.setText("EDITAR");
        btnEditTelefonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTelefonosActionPerformed(evt);
            }
        });

        scLsTelefonos.setViewportView(lsTelefonos);

        txtNueNumero.setToolTipText("Nuevo Numero");

        javax.swing.GroupLayout pnlTelefonosLayout = new javax.swing.GroupLayout(pnlTelefonos);
        pnlTelefonos.setLayout(pnlTelefonosLayout);
        pnlTelefonosLayout.setHorizontalGroup(
            pnlTelefonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelefonosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTelefonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeparadorTelefonos)
                    .addGroup(pnlTelefonosLayout.createSequentialGroup()
                        .addComponent(lblTelefonos)
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelefonosLayout.createSequentialGroup()
                        .addGroup(pnlTelefonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditTelefonos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarTelefonos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddTelefonos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNueNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbTelefonos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTelefonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scLsTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtTelefono))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        pnlTelefonosLayout.setVerticalGroup(
            pnlTelefonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelefonosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTelefonos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTelefonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTelefonos)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTelefonosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTelefonosLayout.createSequentialGroup()
                        .addComponent(btnBorrarTelefonos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditTelefonos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNueNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scLsTelefonos))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelefonos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelefonos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarTelefonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTelefonosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarTelefonosActionPerformed

    private void btnAddTelefonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTelefonosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTelefonosActionPerformed

    private void btnEditTelefonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTelefonosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditTelefonosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SeparadorTelefonos;
    private javax.swing.JButton btnAddTelefonos;
    private javax.swing.JButton btnBorrarTelefonos;
    private javax.swing.JButton btnEditTelefonos;
    private javax.swing.JComboBox<String> cmbTelefonos;
    private javax.swing.JLabel lblTelefonos;
    private javax.swing.JList<String> lsTelefonos;
    private javax.swing.JPanel pnlTelefonos;
    private javax.swing.JScrollPane scLsTelefonos;
    private javax.swing.JTextField txtNueNumero;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
