/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Crear;

import Vista.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Dyl
 */
public class IFrmVehiculosConductor extends javax.swing.JInternalFrame {

    public JButton getAgregar() {
        return Agregar;
    }

    public void setAgregar(JButton Agregar) {
        this.Agregar = Agregar;
    }

    public JButton getBorrar() {
        return Borrar;
    }

    public void setBorrar(JButton Borrar) {
        this.Borrar = Borrar;
    }

    public JList<String> getConductores() {
        return Conductores;
    }

    public void setConductores(JList<String> Conductores) {
        this.Conductores = Conductores;
    }

    public JSeparator getSeparadorAddModCliente() {
        return SeparadorAddModCliente;
    }

    public void setSeparadorAddModCliente(JSeparator SeparadorAddModCliente) {
        this.SeparadorAddModCliente = SeparadorAddModCliente;
    }

    public JList<String> getVehiculosCon() {
        return VehiculosCon;
    }

    public void setVehiculosCon(JList<String> VehiculosCon) {
        this.VehiculosCon = VehiculosCon;
    }

    public JButton getVer() {
        return Ver;
    }

    public void setVer(JButton Ver) {
        this.Ver = Ver;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JLabel getLblAddModCliente() {
        return lblAddModCliente;
    }

    public void setLblAddModCliente(JLabel lblAddModCliente) {
        this.lblAddModCliente = lblAddModCliente;
    }

    public JPanel getPnlAddModCliente() {
        return pnlAddModCliente;
    }

    public void setPnlAddModCliente(JPanel pnlAddModCliente) {
        this.pnlAddModCliente = pnlAddModCliente;
    }

    public JComboBox<String> getVehiculos() {
        return vehiculos;
    }

    public void setVehiculos(JComboBox<String> vehiculos) {
        this.vehiculos = vehiculos;
    }


 

    /**
     * Creates new form IFrmAddModGenerico
     */
    public IFrmVehiculosConductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddModCliente = new javax.swing.JPanel();
        lblAddModCliente = new javax.swing.JLabel();
        SeparadorAddModCliente = new javax.swing.JSeparator();
        Agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Conductores = new javax.swing.JList<>();
        vehiculos = new javax.swing.JComboBox<>();
        Borrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        VehiculosCon = new javax.swing.JList<>();
        Ver = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        pnlAddModCliente.setBackground(new java.awt.Color(255, 255, 255));

        lblAddModCliente.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        lblAddModCliente.setText("Vehiculos Conductor");

        Agregar.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        Agregar.setText("AGREGAR");

        Conductores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Conductores);

        vehiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Borrar.setText("BORRAR");

        VehiculosCon.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(VehiculosCon);

        Ver.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        Ver.setText("VER");

        javax.swing.GroupLayout pnlAddModClienteLayout = new javax.swing.GroupLayout(pnlAddModCliente);
        pnlAddModCliente.setLayout(pnlAddModClienteLayout);
        pnlAddModClienteLayout.setHorizontalGroup(
            pnlAddModClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddModClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddModClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddModClienteLayout.createSequentialGroup()
                        .addComponent(SeparadorAddModCliente)
                        .addContainerGap())
                    .addGroup(pnlAddModClienteLayout.createSequentialGroup()
                        .addComponent(lblAddModCliente)
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(pnlAddModClienteLayout.createSequentialGroup()
                        .addGroup(pnlAddModClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Borrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vehiculos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(Ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(19, 19, 19))))
        );
        pnlAddModClienteLayout.setVerticalGroup(
            pnlAddModClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddModClienteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblAddModCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparadorAddModCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddModClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddModClienteLayout.createSequentialGroup()
                        .addComponent(vehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddModCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddModCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Borrar;
    private javax.swing.JList<String> Conductores;
    private javax.swing.JSeparator SeparadorAddModCliente;
    private javax.swing.JList<String> VehiculosCon;
    private javax.swing.JButton Ver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddModCliente;
    private javax.swing.JPanel pnlAddModCliente;
    private javax.swing.JComboBox<String> vehiculos;
    // End of variables declaration//GEN-END:variables
}
